parameters:
    app.category_icons:
      - paint
      - security
      - smartphone
      - tablet
      - laptop
      - desktop
      - travel-car
      - travel-bus
      - train
      - gas-station
      - ev-station
      - flight-takeoff
      - earth
      - donation
      - housing
      - store
      - bank
      - gavel
      - hospital
      - construction
      - hammer
      - cases
      - wallet
      - credit-card
      - cart
      - pets
      - clothes
      - hairdresser
      - spa
      - smoking
      - nightlife
      - gaming
      - gift
      - cake
      - fastfood
      - food