parameters:
    app.category_icons:
      - paint
      - security
      - smartphone
      - tablet
      - laptop
      - desktop
      - travel-car
      - two-wheelers
      - travel-bus
      - travel-taxi
      - train
      - tram
      - travel-boat
      - bike
      - electric-bike
      - electric-scooter
      - gas-station
      - ev-station
      - flight-takeoff
      - earth
      - donation
      - housing
      - apartment
      - store
      - storefront
      - bank
      - gavel
      - hospital
      - construction
      - hammer
      - cases
      - wallet
      - credit-card
      - cart
      - pets
      - clothes
      - hairdresser
      - spa
      - smoking
      - nightlife
      - gaming
      - gift
      - cake
      - fastfood
      - food